version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - hu553in
    commit-message:
      prefix: 'deps(github-actions):'
    allow:
      - dependency-type: all
    groups:
      patch-and-minor:
        update-types:
          - patch
          - minor
      major:
        update-types:
          - major
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - hu553in
    commit-message:
      prefix: 'deps(npm):'
    allow:
      - dependency-type: all
    groups:
      patch-and-minor:
        update-types:
          - patch
          - minor
      major:
        update-types:
          - major
