name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml2-utils
          version: 1.0
      - run: pnpm check
