name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_type != 'tag' }}

jobs:
  check:
    permissions:
      contents: read
    uses: hu553in/common-things/.github/workflows/check-bun.yml@main
    with:
      cache_eslint: true
